services:
  postgres:
    image: postgres:17
    container_name: bun-auth-postgres
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bun-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bun-auth-jaeger
    ports:
      - "16686:16686"  # UI do Jaeger
      - "4318:4318"    # OTLP HTTP (sua app envia aqui)
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  postgres_data:
  redis_data: